apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-noticia-deployment
spec:
  selector:
    matchLabels:
      name: aplicacao-noticia-pod
  template:
    metadata:
      labels:
        name: aplicacao-noticia-pod
    spec:
      containers:
        - name: container-aplicacao-cpu
          image: saulocn/noticia-alura:2
          resources:
              requests:
                cpu: 400m
          ports:
            - containerPort: 80
