apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        name: nginx
    spec:
      replicas: 3
      containers:
        - name: container-kubernetes
          image: nginx