apiVersion: v1
kind: Service
metadata:
  name: servico-sistema-noticia-statefulset
spec:
  type: LoadBalancer
  ports:
  - port: 80
    name: http
    nodePort: 32348
  selector:
    name: aplicacao-sistema-pod-statefulset
